[package]
name = "ipfsdag"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
types = { path = "../types" }
eyre = "0.6.5"
serde = "1.0.152"
serde_json = "1.0.91"
base64 = "0.20.0"