[package]
name = "types"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eyre = "0.6.5"
serde = "1.0.152"
serde_json = "1.0.91"
rlp = "0.5.1"
rlp-derive = "0.1.0"
sha2 = "0.10.6"
bs58 = "0.4.0"